/**
 *
 * $Id$
 */
package fr.mutualite.rh.model.dto.validation;

import fr.mutualite.rh.model.Employe;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link fr.mutualite.rh.model.dto.Etablissement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EtablissementValidator {
	boolean validate();

	boolean validateNom(String value);
	boolean validateEmployes(EList<Employe> value);
	boolean validateId(int value);
	boolean validateResponsable(Employe value);
}
