/**
 *
 * $Id$
 */
package fr.mutualite.rh.model.dto.validation;

import fr.mutualite.rh.model.Entretien;

import java.util.Date;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link fr.mutualite.rh.model.dto.Formulaire}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface FormulaireValidator {
	boolean validate();

	boolean validatePrenom(String value);
	boolean validateMatricule(int value);
	boolean validateNom(String value);
	boolean validateDiplomes(String value);

	boolean validateDiplomes(EList<String> value);
	boolean validateService(String value);
	boolean validatePoste(String value);
	boolean validateResponsable(String value);
	boolean validateMenePar(String value);
	boolean validateEntretien(Entretien value);
	boolean validateDate(Date value);
	boolean validateDatePrecedentEntretien(Date value);

	boolean validateAnciennete(String value);

	boolean validateDateEntreeEntreprise(Date value);
}
