/**
 *
 * $Id$
 */
package fr.mutualite.rh.model.dto.validation;


/**
 * A sample validator interface for {@link fr.mutualite.rh.model.dto.UIEmploye}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UIEmployeValidator {
	boolean validate();

	boolean validatePrenom(String value);
	boolean validateMatricule(int value);
	boolean validateNom(String value);
}
