<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="chequedej" nsURI="http://www.mutualite.fr/chequedej/1.0" nsPrefix="chequedej">
  <eClassifiers xsi:type="ecore:EClass" name="Succursale">
    <eOperations name="codeClient" eType="#//CodeClient"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numero" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idEtablissement" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CodeClient">
    <eStructuralFeatures xsi:type="ecore:EReference" name="succursales" upperBound="-1"
        eType="#//Succursale" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numero" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="libelle" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChequeDej">
    <eOperations name="integrateDeje">
      <eParameters name="mois" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="matricule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="nbEstimeJoursEntiers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="nbReelJoursEntiers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="carnet" lowerBound="1"
        eType="#//Carnet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valeurNominale" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="6.7"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="participationPatronale"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="3.69"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="etablissementsVirtuels"
        lowerBound="1" eType="#//EtablissementsVirtuels" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parametrage" lowerBound="1"
        eType="#//Parametrage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stock" lowerBound="1" eType="#//Stock"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="solde" lowerBound="1" eType="#//Solde"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dejes" lowerBound="1" eType="#//Deje"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="choix" lowerBound="1" eType="#//Choix"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commandeMaxParDefaut" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="25"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contrats" lowerBound="1"
        eType="#//Contrats" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Commande">
    <eOperations name="carnet" eType="#//Carnet"/>
    <eOperations name="getOrCreateItem" eType="#//Item">
      <eParameters name="matricule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//Item" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="participationPatronale"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="3.58"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valeurNominale" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="6.5"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mois" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commandePrecedente" eType="#//Commande"
        eOpposite="#//Commande/commandeSuivante"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commandeSuivante" eType="#//Commande"
        eOpposite="#//Commande/commandePrecedente"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item">
    <eStructuralFeatures xsi:type="ecore:EReference" name="succursale" lowerBound="1"
        eType="#//Succursale"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="matricule" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbCheques" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commentaire" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prenom" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EtablissementVirtuel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="matriculesEmployes" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="libelle" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Carnet">
    <eOperations name="root" eType="#//ChequeDej"/>
    <eOperations name="getOrCreateCommande" eType="#//Commande">
      <eParameters name="mois" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commandes" upperBound="-1"
        eType="#//Commande" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EtablissementsVirtuels">
    <eStructuralFeatures xsi:type="ecore:EReference" name="etablissementsVirtuels"
        upperBound="-1" eType="#//EtablissementVirtuel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parametrage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="codesClient" upperBound="-1"
        eType="#//CodeClient" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cheque" upperBound="-1"
        eType="#//Cheque" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derniereMaj" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cheque">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="matricule" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbCheques" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Solde">
    <eOperations name="getOrCreateSoldeIndividual" eType="#//SoldeIndividuel">
      <eParameters name="matricule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="getSolde" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eParameters name="matricule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="annee" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eParameters name="mois" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getSoldeIndividual" eType="#//SoldeIndividuel">
      <eParameters name="matricule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="soldesIndividuels" upperBound="-1"
        eType="#//SoldeIndividuel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SoldeIndividuel">
    <eOperations name="incremente">
      <eParameters name="delta" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eParameters name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbCheques" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="matricule" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="historique" upperBound="-1"
        eType="#//HistoriqueSoldeIndividuel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="annee" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HistoriqueSoldeIndividuel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="soldeAvant" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="soldeApres" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Deje">
    <eOperations name="getOrCreateDejeMensuel" eType="#//DejeMensuel">
      <eParameters name="mois" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="root" eType="#//ChequeDej"/>
    <eOperations name="getDejeMensuel" eType="#//DejeMensuel">
      <eParameters name="mois" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dejesMensuels" upperBound="-1"
        eType="#//DejeMensuel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DejeIndividuel">
    <eOperations name="dejeMensuel" eType="#//DejeMensuel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbEstimeJoursEntiers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="matricule" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbReelJoursEntiers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="avance" eType="#//Avance"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DejeMensuel">
    <eOperations name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="getOrCreateDejeIndividuel" eType="#//DejeIndividuel">
      <eParameters name="matricule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="deje" eType="#//Deje"/>
    <eOperations name="getDejeIndividuel" eType="#//DejeIndividuel">
      <eParameters name="matricule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dejesIndividuels" upperBound="-1"
        eType="#//DejeIndividuel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mois" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Choix">
    <eOperations name="getChoix" eType="#//ChoixIndividuel">
      <eParameters name="matricule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="getOrCreateChoix" eType="#//ChoixIndividuel">
      <eParameters name="matricule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="choixIndividuels" upperBound="-1"
        eType="#//ChoixIndividuel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChoixIndividuel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbMaxCheques" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="matricule" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contrats">
    <eOperations name="getOrCreateContrat" eType="#//Contrat">
      <eParameters name="matricule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="isPartiel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="matricule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contrats" upperBound="-1"
        eType="#//Contrat" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contrat">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tempsTravailMensuel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="partiel" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" changeable="false"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="matricule" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Avance">
    <eOperations name="dejeIndividuel" eType="#//DejeIndividuel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbCheques" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
