<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="conges" nsURI="http://www.mutualite.fr/conges/1.0" nsPrefix="conges">
  <eClassifiers xsi:type="ecore:EClass" name="Employe">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="matricule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="etablissement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conges" upperBound="-1"
        eType="#//Conge" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conge">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="debut" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//TypeConge"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="decompte" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TypeConge">
    <eLiterals name="CP" value="950" literal="Congés Payés"/>
    <eLiterals name="ANCIENNETE" value="951" literal="Congés d'Ancienneté"/>
    <eLiterals name="FRACTIONNEMENT" value="952" literal="Congés de Fractionnement"/>
    <eLiterals name="PONT" value="955" literal="Pont"/>
    <eLiterals name="SOLIDARITE" value="953" literal="Congé Solidarité"/>
  </eClassifiers>
</ecore:EPackage>
