/**
 *
 * $Id$
 */
package fr.mutualite.rh.model.validation;

import fr.mutualite.rh.model.ClassificationStatut;

import java.util.Date;

/**
 * A sample validator interface for {@link fr.mutualite.rh.model.AffectationClassification}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AffectationClassificationValidator {
	boolean validate();

	boolean validateDateDebut(Date value);
	boolean validateDateFin(Date value);
	boolean validateClassification(ClassificationStatut value);
}
