/**
 *
 * $Id$
 */
package fr.mutualite.rh.model.validation;

import fr.mutualite.rh.model.Appreciation;
import fr.mutualite.rh.model.SessionFormation;
import java.util.Date;

/**
 * A sample validator interface for {@link fr.mutualite.rh.model.AppreciationSessionFormation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AppreciationSessionFormationValidator {
	boolean validate();

	boolean validateValeur(Appreciation value);
	boolean validateSessionFormation(SessionFormation value);

	boolean validateIdFormation(String value);

	boolean validateIdFormation(Long value);

	boolean validateLibelleFormation(String value);

	boolean validateDateFormation(String value);

	boolean validateDateFormation(Date value);

	boolean validateSessionformation(SessionFormation value);
}
