/**
 *
 * $Id$
 */
package fr.mutualite.rh.model.validation;

import fr.mutualite.rh.model.Employe;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link fr.mutualite.rh.model.Effectif}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EffectifValidator {
	boolean validate();

	boolean validateEmployes(EList<Employe> value);
}
