/**
 *
 * $Id$
 */
package fr.mutualite.rh.model.validation;

import fr.mutualite.rh.model.Affectation;
import fr.mutualite.rh.model.AffectationClassification;
import fr.mutualite.rh.model.Employe;
import fr.mutualite.rh.model.Entretien;
import fr.mutualite.rh.model.Etablissement;
import fr.mutualite.rh.model.SessionFormation;

import java.util.Date;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link fr.mutualite.rh.model.Employe}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EmployeValidator {
	boolean validate();

	boolean validateMatricule(int value);
	boolean validatePrenom(String value);
	boolean validateNom(String value);
	boolean validateNomJeuneFille(String value);
	boolean validateDateNaissance(Date value);
	boolean validateDateEmbauche(Date value);
	boolean validateDiplomes(EList<String> value);
	boolean validateEtablissement(Etablissement value);
	boolean validateAffectationsEmploi(EList<Affectation> value);
	boolean validateAffectationEmploiCourante(Affectation value);
	boolean validateAffectationsClassification(EList<AffectationClassification> value);
	boolean validateAffectationClassificationCourante(AffectationClassification value);
	boolean validateSessionsFormation(EList<SessionFormation> value);

	boolean validateEntretien(EList<Entretien> value);

	boolean validateEntretiens(EList<Entretien> value);

	boolean validateEntretiensMenes(EList<Entretien> value);

	boolean validateDateSortieEntreprise(Date value);

	boolean validateResponsable(Employe value);

	boolean validateSubalternes(EList<Employe> value);

	boolean validateEtablissementsEnResponsabilite(EList<Etablissement> value);

	boolean validateEntreteneurs(EList<Employe> value);

	boolean validateEmployesEntretenus(EList<Employe> value);
}
