/**
 *
 * $Id$
 */
package fr.mutualite.rh.model.validation;

import fr.mutualite.rh.model.AppreciationSessionFormation;
import fr.mutualite.rh.model.SouhaitFormationEvaluateur;
import fr.mutualite.rh.model.SouhaitFormationSalarie;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link fr.mutualite.rh.model.EntretienProfessionnel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EntretienProfessionnelValidator {
	boolean validate();

	boolean validateEvolutionDepuisDernierEntretien(String value);
	boolean validateCommentaireBilanFormation(String value);
	boolean validateEvolutionSouhaiteeDansEmploiActuel(String value);
	boolean validateEvolutionSouhaiteeDansNouvelEmploi(String value);
	boolean validateEcheance(String value);
	boolean validateEvolutionSouhaiteeCompetencesAcquises(String value);
	boolean validateEvolutionSouhaiteeCompetencesRequises(String value);
	boolean validateEvolutionSouhaiteeMoyensRealisation(String value);
	boolean validateAutresActionsDeveloppementCompetences(String value);
	boolean validatePerspectivesEvolutionProfessionnelle(String value);
	boolean validatePerspectivesEvolutionProfessionnelleCompetencesAssociees(String value);
	boolean validateAdequationProjetProBesoinsEntreprise(Boolean value);
	boolean validateAdequationProjetProBesoinsEntrepriseCommentaire(String value);
	boolean validateRencontreRh(boolean value);
	boolean validateRencontreRhCommentaire(String value);
	boolean validateSynthese(String value);
	boolean validateAppreciationsSessionFormation(EList<AppreciationSessionFormation> value);

	boolean validateAppreciationsessionformation(EList<AppreciationSessionFormation> value);
	boolean validateSouhaitsFormationSalarie(EList<SouhaitFormationSalarie> value);
	boolean validateSouhaitsFormationEvaluateur(EList<SouhaitFormationEvaluateur> value);
}
