/**
 *
 * $Id$
 */
package fr.mutualite.rh.model.validation;

import fr.mutualite.rh.model.Effectif;
import fr.mutualite.rh.model.Emplois;
import fr.mutualite.rh.model.Etablissements;
import fr.mutualite.rh.model.Organismes;
import fr.mutualite.rh.model.Utilisateur;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link fr.mutualite.rh.model.Mutualite}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MutualiteValidator {
	boolean validate();

	boolean validateEtablissements(Etablissements value);
	boolean validateEmplois(Emplois value);
	boolean validateEffectif(Effectif value);
	boolean validateOrganismes(Organismes value);

	boolean validateUtilisateurs(EList<Utilisateur> value);
}
