/**
 *
 * $Id$
 */
package fr.mutualite.rh.model.validation;

import fr.mutualite.rh.model.AppreciationSessionFormation;
import fr.mutualite.rh.model.Employe;

import java.util.Date;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link fr.mutualite.rh.model.SessionFormation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SessionFormationValidator {
	boolean validate();

	boolean validateDateFin(Date value);
	boolean validateDateDebut(Date value);
	boolean validateDuree(Float value);

	boolean validateDuree(int value);
	boolean validateEmployes(EList<Employe> value);

	boolean validateAppreciations(EList<AppreciationSessionFormation> value);
}
