/**
 *
 * $Id$
 */
package fr.mutualite.rh.model.validation;

import fr.mutualite.rh.model.Avis;

/**
 * A sample validator interface for {@link fr.mutualite.rh.model.SouhaitFormationSalarie}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SouhaitFormationSalarieValidator {
	boolean validate();

	boolean validateTexte(String value);
	boolean validateAvisEvaluateur(Avis value);

	boolean validateId(long value);
}
