/**
 *
 * $Id$
 */
package fr.mutualite.rh.model.validation;

import fr.mutualite.rh.model.Employe;
import fr.mutualite.rh.model.Role;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link fr.mutualite.rh.model.Utilisateur}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UtilisateurValidator {
	boolean validate();

	boolean validateEmploye(Employe value);
	boolean validateLogin(String value);
	boolean validateDn(String value);
	boolean validateRoles(EList<Role> value);
}
